import { PropertyData } from './properties';
import React from 'react';
import {
  IconRuler,
  IconBuilding,
  IconDoor,
  IconBed,
  IconShower,
  IconBath,
} from '@/components/icons';

/* ── Biens en location ────────────────────────────────────── */
export const RENTALS: PropertyData[] = [
  {
    id: 'studio-marais-paris',
    title: 'Studio meublé au cœur du Marais',
    location: '75004 Paris',
    price: '1 150 €/mois',
    pricePerM2: '46 €/m²',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    specs: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: '25 m²' },
      { icon: React.createElement(IconBuilding, { size: 24 }), label: '4ème étage' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: '1 pièce' },
      { icon: React.createElement(IconBed, { size: 24 }), label: '1 chambre' },
      { icon: React.createElement(IconShower, { size: 24 }), label: "1 salle d'eau" },
    ],
    description: [
      "Charmant studio meublé de 25 m² idéalement situé dans le quartier historique du Marais.",
      "Entièrement refait à neuf, il dispose d'une kitchenette équipée et d'une salle d'eau moderne.",
    ],
    characteristics: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: 'Surface', value: '25 m²' },
      { icon: React.createElement(IconBuilding, { size: 24 }), label: 'Étage', value: '4ème' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: 'Pièces', value: '1' },
      { icon: React.createElement(IconBed, { size: 24 }), label: 'Chambres', value: '1' },
      { icon: React.createElement(IconShower, { size: 24 }), label: "Salle d'eau", value: '1' },
    ],
    specificites: ['Meublé', 'Double vitrage', 'Cuisine équipée', 'Parquet'],
    dpe: { grade: 'D', value: 200 },
    ges: { grade: 'C', value: 120 },
    copropriete: [
      { label: 'Charges comprises', value: '50 €/mois' },
      { label: 'Dépôt de garantie', value: '1 150 €' },
    ],
    environnement: ['Métro', 'Bus', 'Commerces', 'Restaurant', 'Parc'],
    pricingDetails: [
      { label: 'Loyer charges comprises', value: '1 200 €/mois' },
      { label: 'Honoraires', value: '500 €' },
    ],
    advertiser: { name: 'ParisLoc', address: '15 rue de Rivoli, 75004 Paris', siret: '912345000', carte: 'CPI 7501 2023 000 000 001' },
    coordinates: { lat: 48.8566, lng: 2.3522 },
    reference: 'loc-001',
    cardTitle: 'Studio meublé – Le Marais',
    cardLocation: 'Paris 4e, Île-de-France',
    cardPrice: '1 150 €/mois',
    cardFeatures: [{ label: '1 pièce' }, { label: '25 m²' }],
    badgeLabel: 'Vient d\'arriver',
    badgeColor: 'green',
    lifestyle: ['dynamic', 'connected'],
  },
  {
    id: 'appartement-lyon-6',
    title: 'T3 lumineux avec balcon à Lyon 6e',
    location: '69006 Lyon',
    price: '950 €/mois',
    pricePerM2: '15,83 €/m²',
    images: [
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
    ],
    specs: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: '60 m²' },
      { icon: React.createElement(IconBuilding, { size: 24 }), label: '2ème étage' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: '3 pièces' },
      { icon: React.createElement(IconBed, { size: 24 }), label: '2 chambres' },
      { icon: React.createElement(IconBath, { size: 24 }), label: '1 salle de bain' },
    ],
    description: [
      "Bel appartement T3 de 60 m² au 2e étage dans le prestigieux 6e arrondissement de Lyon.",
      "Séjour lumineux ouvert sur un balcon de 8 m². Deux chambres, cuisine équipée, salle de bain.",
    ],
    characteristics: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: 'Surface', value: '60 m²' },
      { icon: React.createElement(IconBuilding, { size: 24 }), label: 'Étage', value: '2ème' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: 'Pièces', value: '3' },
      { icon: React.createElement(IconBed, { size: 24 }), label: 'Chambres', value: '2' },
      { icon: React.createElement(IconBath, { size: 24 }), label: 'Salle de bain', value: '1' },
    ],
    specificites: ['Balcon', 'Ascenseur', 'Cave', 'Cuisine équipée', 'Double vitrage'],
    dpe: { grade: 'C', value: 140 },
    ges: { grade: 'B', value: 80 },
    copropriete: [
      { label: 'Charges comprises', value: '70 €/mois' },
      { label: 'Dépôt de garantie', value: '950 €' },
    ],
    environnement: ['Métro', 'Tram', 'Parc de la Tête d\'Or', 'Commerces', 'Universités'],
    pricingDetails: [
      { label: 'Loyer charges comprises', value: '1 020 €/mois' },
      { label: 'Honoraires', value: '600 €' },
    ],
    advertiser: { name: 'Lyon Habitat', address: '22 rue de la République, 69006 Lyon', siret: '823456000', carte: 'CPI 6901 2021 000 012 000' },
    coordinates: { lat: 45.7676, lng: 4.8516 },
    reference: 'loc-002',
    cardTitle: 'T3 lumineux avec balcon',
    cardLocation: 'Lyon 6e, Rhône',
    cardPrice: '950 €/mois',
    cardFeatures: [{ label: '3 pièces' }, { label: '60 m²' }],
    badgeLabel: 'Coup de cœur',
    badgeColor: 'blue',
    lifestyle: ['family', 'green', 'connected'],
  },
  {
    id: 'maison-jardin-bordeaux',
    title: 'Maison 4 pièces avec jardin à Bordeaux',
    location: '33000 Bordeaux',
    price: '1 400 €/mois',
    pricePerM2: '15,56 €/m²',
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
      'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=80',
      'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=80',
    ],
    specs: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: '90 m²' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: '4 pièces' },
      { icon: React.createElement(IconBed, { size: 24 }), label: '3 chambres' },
      { icon: React.createElement(IconBath, { size: 24 }), label: '1 salle de bain' },
      { icon: React.createElement(IconShower, { size: 24 }), label: "1 salle d'eau" },
    ],
    description: [
      "Maison de ville de 90 m² avec jardin privatif de 80 m², idéalement située dans le quartier des Chartrons.",
      "Rez-de-chaussée : séjour, cuisine ouverte. Étage : 3 chambres, salle de bain. Garage.",
    ],
    characteristics: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: 'Surface', value: '90 m²' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: 'Pièces', value: '4' },
      { icon: React.createElement(IconBed, { size: 24 }), label: 'Chambres', value: '3' },
      { icon: React.createElement(IconBath, { size: 24 }), label: 'Salle de bain', value: '1' },
      { icon: React.createElement(IconShower, { size: 24 }), label: "Salle d'eau", value: '1' },
    ],
    specificites: ['Jardin', 'Garage', 'Cuisine équipée', 'Cheminée', 'Parquet'],
    dpe: { grade: 'D', value: 180 },
    ges: { grade: 'C', value: 130 },
    copropriete: [
      { label: 'Charges comprises', value: '0 €' },
      { label: 'Dépôt de garantie', value: '1 400 €' },
    ],
    environnement: ['Tram', 'Commerces', 'Marché des Chartrons', 'Jardin public', 'Écoles'],
    pricingDetails: [
      { label: 'Loyer hors charges', value: '1 400 €/mois' },
      { label: 'Honoraires', value: '900 €' },
    ],
    advertiser: { name: 'Bordeaux Immo', address: '5 cours du Chapeau Rouge, 33000 Bordeaux', siret: '734567000', carte: 'CPI 3301 2019 000 045 000' },
    coordinates: { lat: 44.8378, lng: -0.5792 },
    reference: 'loc-003',
    cardTitle: 'Maison avec jardin – Chartrons',
    cardLocation: 'Bordeaux, Gironde',
    cardPrice: '1 400 €/mois',
    cardFeatures: [{ label: '4 pièces' }, { label: '90 m²' }],
    badgeLabel: 'Bon plan',
    badgeColor: 'orange',
    lifestyle: ['family', 'quiet', 'green'],
  },
  {
    id: 't2-nantes-centre',
    title: 'T2 rénové proche gare de Nantes',
    location: '44000 Nantes',
    price: '720 €/mois',
    pricePerM2: '18 €/m²',
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
      'https://images.unsplash.com/photo-1484154218962-a197022b5858?w=800&q=80',
    ],
    specs: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: '40 m²' },
      { icon: React.createElement(IconBuilding, { size: 24 }), label: '3ème étage' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: '2 pièces' },
      { icon: React.createElement(IconBed, { size: 24 }), label: '1 chambre' },
      { icon: React.createElement(IconShower, { size: 24 }), label: "1 salle d'eau" },
    ],
    description: [
      "Appartement T2 rénové de 40 m² à 5 minutes à pied de la gare de Nantes.",
      "Séjour lumineux, chambre séparée, salle d'eau avec douche italienne. Cave en sous-sol.",
    ],
    characteristics: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: 'Surface', value: '40 m²' },
      { icon: React.createElement(IconBuilding, { size: 24 }), label: 'Étage', value: '3ème' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: 'Pièces', value: '2' },
      { icon: React.createElement(IconBed, { size: 24 }), label: 'Chambres', value: '1' },
      { icon: React.createElement(IconShower, { size: 24 }), label: "Salle d'eau", value: '1' },
    ],
    specificites: ['Rénové', 'Cave', 'Proche transports', 'Cuisine équipée'],
    dpe: { grade: 'C', value: 130 },
    ges: { grade: 'B', value: 75 },
    copropriete: [
      { label: 'Charges comprises', value: '40 €/mois' },
      { label: 'Dépôt de garantie', value: '720 €' },
    ],
    environnement: ['Gare TGV', 'Tram', 'Commerces', 'Parc', 'Universités'],
    pricingDetails: [
      { label: 'Loyer charges comprises', value: '760 €/mois' },
      { label: 'Honoraires', value: '400 €' },
    ],
    advertiser: { name: 'Nantes Loc', address: '8 place du Commerce, 44000 Nantes', siret: '645678000', carte: 'CPI 4401 2022 000 023 000' },
    coordinates: { lat: 47.2184, lng: -1.5536 },
    reference: 'loc-004',
    cardTitle: 'T2 rénové proche gare',
    cardLocation: 'Nantes, Loire-Atlantique',
    cardPrice: '720 €/mois',
    cardFeatures: [{ label: '2 pièces' }, { label: '40 m²' }],
    badgeLabel: 'Vient d\'arriver',
    badgeColor: 'green',
    lifestyle: ['student', 'connected'],
  },
  {
    id: 'appartement-nice-promenade',
    title: 'T3 vue mer sur la Promenade des Anglais',
    location: '06000 Nice',
    price: '1 800 €/mois',
    pricePerM2: '25,71 €/m²',
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800&q=80',
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?w=800&q=80',
      'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&q=80',
    ],
    specs: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: '70 m²' },
      { icon: React.createElement(IconBuilding, { size: 24 }), label: '6ème étage' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: '3 pièces' },
      { icon: React.createElement(IconBed, { size: 24 }), label: '2 chambres' },
      { icon: React.createElement(IconBath, { size: 24 }), label: '1 salle de bain' },
    ],
    description: [
      "Magnifique T3 de 70 m² au 6e étage avec vue imprenable sur la mer et la Promenade des Anglais.",
      "Grand séjour-salon, balcon filant, deux chambres, salle de bain rénovée. Résidence sécurisée avec gardien.",
    ],
    characteristics: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: 'Surface', value: '70 m²' },
      { icon: React.createElement(IconBuilding, { size: 24 }), label: 'Étage', value: '6ème' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: 'Pièces', value: '3' },
      { icon: React.createElement(IconBed, { size: 24 }), label: 'Chambres', value: '2' },
      { icon: React.createElement(IconBath, { size: 24 }), label: 'Salle de bain', value: '1' },
    ],
    specificites: ['Vue mer', 'Balcon', 'Ascenseur', 'Gardien', 'Climatisation', 'Parking'],
    dpe: { grade: 'C', value: 110 },
    ges: { grade: 'B', value: 70 },
    copropriete: [
      { label: 'Charges comprises', value: '100 €/mois' },
      { label: 'Dépôt de garantie', value: '1 800 €' },
    ],
    environnement: ['Plage', 'Tram', 'Commerces', 'Restaurant', 'Aéroport'],
    pricingDetails: [
      { label: 'Loyer charges comprises', value: '1 900 €/mois' },
      { label: 'Honoraires', value: '1 000 €' },
    ],
    advertiser: { name: 'Riviera Immo', address: '12 Promenade des Anglais, 06000 Nice', siret: '556789000', carte: 'CPI 0601 2020 000 067 000' },
    coordinates: { lat: 43.6945, lng: 7.2653 },
    reference: 'loc-005',
    cardTitle: 'T3 vue mer – Promenade',
    cardLocation: 'Nice, Alpes-Maritimes',
    cardPrice: '1 800 €/mois',
    cardFeatures: [{ label: '3 pièces' }, { label: '70 m²' }],
    badgeLabel: 'Dernière chance',
    badgeColor: 'amber',
    lifestyle: ['view', 'beach', 'dynamic'],
  },
  {
    id: 'loft-lille-vauban',
    title: 'Loft atypique quartier Vauban à Lille',
    location: '59000 Lille',
    price: '1 100 €/mois',
    pricePerM2: '13,75 €/m²',
    images: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=80',
    ],
    specs: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: '80 m²' },
      { icon: React.createElement(IconBuilding, { size: 24 }), label: '1er étage' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: '3 pièces' },
      { icon: React.createElement(IconBed, { size: 24 }), label: '2 chambres' },
      { icon: React.createElement(IconShower, { size: 24 }), label: "1 salle d'eau" },
    ],
    description: [
      "Loft atypique de 80 m² dans un ancien entrepôt rénové, quartier Vauban à Lille.",
      "Volumes généreux, verrière, cuisine ouverte, deux chambres en mezzanine. Charme et caractère.",
    ],
    characteristics: [
      { icon: React.createElement(IconRuler, { size: 24 }), label: 'Surface', value: '80 m²' },
      { icon: React.createElement(IconBuilding, { size: 24 }), label: 'Étage', value: '1er' },
      { icon: React.createElement(IconDoor, { size: 24 }), label: 'Pièces', value: '3' },
      { icon: React.createElement(IconBed, { size: 24 }), label: 'Chambres', value: '2' },
      { icon: React.createElement(IconShower, { size: 24 }), label: "Salle d'eau", value: '1' },
    ],
    specificites: ['Loft', 'Verrière', 'Mezzanine', 'Parquet', 'Cuisine ouverte'],
    dpe: { grade: 'D', value: 190 },
    ges: { grade: 'C', value: 125 },
    copropriete: [
      { label: 'Charges comprises', value: '80 €/mois' },
      { label: 'Dépôt de garantie', value: '1 100 €' },
    ],
    environnement: ['Métro', 'Université', 'Commerces', 'Parc', 'Restaurants'],
    pricingDetails: [
      { label: 'Loyer charges comprises', value: '1 180 €/mois' },
      { label: 'Honoraires', value: '700 €' },
    ],
    advertiser: { name: 'Lille Habitat', address: '3 place de la République, 59000 Lille', siret: '467890000', carte: 'CPI 5901 2021 000 034 000' },
    coordinates: { lat: 50.6292, lng: 3.0573 },
    reference: 'loc-006',
    cardTitle: 'Loft atypique – Vauban',
    cardLocation: 'Lille, Nord',
    cardPrice: '1 100 €/mois',
    cardFeatures: [{ label: '3 pièces' }, { label: '80 m²' }],
    badgeLabel: 'Pépite rare',
    badgeColor: 'purple',
    lifestyle: ['student', 'dynamic'],
  },
];
